// Code generated by thriftgo (0.3.17). DO NOT EDIT.

package service

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ServiceCategory int64

const (
	ServiceCategory_FEATURE ServiceCategory = 0
	ServiceCategory_MVT     ServiceCategory = 1
	ServiceCategory_WMTS    ServiceCategory = 2
)

func (p ServiceCategory) String() string {
	switch p {
	case ServiceCategory_FEATURE:
		return "FEATURE"
	case ServiceCategory_MVT:
		return "MVT"
	case ServiceCategory_WMTS:
		return "WMTS"
	}
	return "<UNSET>"
}

func ServiceCategoryFromString(s string) (ServiceCategory, error) {
	switch s {
	case "FEATURE":
		return ServiceCategory_FEATURE, nil
	case "MVT":
		return ServiceCategory_MVT, nil
	case "WMTS":
		return ServiceCategory_WMTS, nil
	}
	return ServiceCategory(0), fmt.Errorf("not a valid ServiceCategory string")
}

func ServiceCategoryPtr(v ServiceCategory) *ServiceCategory { return &v }
func (p *ServiceCategory) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ServiceCategory(result.Int64)
	return
}

func (p *ServiceCategory) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
