// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cloud_tinamic/rpc/service_collection/repo"
)

// Injectors from wire.go:

func InitServiceCollection() (*ServiceCollectionImpl, error) {
	client, err := NewMapProcessorClient()
	if err != nil {
		return nil, err
	}
	storeserviceClient, err := NewGeoServiceClient()
	if err != nil {
		return nil, err
	}
	db := repo.NewDB()
	serviceCollectionRepo := repo.NewServiceCollectionRepoImpl(db)
	sourceserviceClient, err := NewSourceServiceClient()
	if err != nil {
		return nil, err
	}
	serviceCollectionImpl := NewServiceCollectionImpl(client, storeserviceClient, serviceCollectionRepo, sourceserviceClient)
	return serviceCollectionImpl, nil
}
