// Code generated by Kitex v0.11.3. DO NOT EDIT.

package storeservice

import (
	storage "cloud_tinamic/kitex_gen/data/storage"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	VectorStorage(ctx context.Context, req *storage.StoreRequest, callOptions ...callopt.Option) (r *storage.StoreResponse, err error)
	ToGeoParquetStorage(ctx context.Context, req *storage.ToGeoParquetStorageRequest, callOptions ...callopt.Option) (r *storage.ToGeoParquetStorageResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kStoreServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStoreServiceClient struct {
	*kClient
}

func (p *kStoreServiceClient) VectorStorage(ctx context.Context, req *storage.StoreRequest, callOptions ...callopt.Option) (r *storage.StoreResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VectorStorage(ctx, req)
}

func (p *kStoreServiceClient) ToGeoParquetStorage(ctx context.Context, req *storage.ToGeoParquetStorageRequest, callOptions ...callopt.Option) (r *storage.ToGeoParquetStorageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ToGeoParquetStorage(ctx, req)
}
