// Code generated by Kitex v0.11.0. DO NOT EDIT.

package storeservice

import (
	storage "cloud_tinamic/kitex_gen/data/storage"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"VectorStorage": kitex.NewMethodInfo(
		vectorStorageHandler,
		newStoreServiceVectorStorageArgs,
		newStoreServiceVectorStorageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	storeServiceServiceInfo                = NewServiceInfo()
	storeServiceServiceInfoForClient       = NewServiceInfoForClient()
	storeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return storeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return storeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return storeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StoreService"
	handlerType := (*storage.StoreService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "storage",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.11.0",
		Extra:           extra,
	}
	return svcInfo
}

func vectorStorageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*storage.StoreServiceVectorStorageArgs)
	realResult := result.(*storage.StoreServiceVectorStorageResult)
	success, err := handler.(storage.StoreService).VectorStorage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStoreServiceVectorStorageArgs() interface{} {
	return storage.NewStoreServiceVectorStorageArgs()
}

func newStoreServiceVectorStorageResult() interface{} {
	return storage.NewStoreServiceVectorStorageResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) VectorStorage(ctx context.Context, req *storage.StoreRequest) (r *storage.StoreResponse, err error) {
	var _args storage.StoreServiceVectorStorageArgs
	_args.Req = req
	var _result storage.StoreServiceVectorStorageResult
	if err = p.c.Call(ctx, "VectorStorage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
