// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cloud_tinamic/rpc/source/repo"
	"github.com/google/wire"
)

// Injectors from wire.go:

// SourceService 注入优化
func InitSourceService() (*SourceServiceImpl, error) {
	db := repo.NewDB()
	storage := repo.NewMinio()
	sourceRepo := repo.NewSourceRepoImpl(db, storage)
	client, err := NewGeoServiceClient()
	if err != nil {
		return nil, err
	}
	sourceServiceImpl := NewSourceServiceImpl(sourceRepo, client)
	return sourceServiceImpl, nil
}

// NSQ Client 注入优化
func InitNsqClient() *repo.NsqConsumer {
	nsqConfig := repo.NewNsqConfig()
	db := repo.NewDB()
	storage := repo.NewMinio()
	sourceRepo := repo.NewSourceRepoImpl(db, storage)
	handler := repo.NewNSQHandler(sourceRepo)
	nsqConsumer := repo.NewNsqConsumer(nsqConfig, handler)
	return nsqConsumer
}

// wire.go:

// 定义数据库的 ProviderSet
var DatabaseProviders = wire.NewSet(repo.NewDB, repo.NewSourceRepoImpl)

// 定义 MinIO 的 ProviderSet
var MinioProviders = wire.NewSet(repo.NewMinio)

// 组合所有 Providers，复用依赖
var DataProviders = wire.NewSet(
	DatabaseProviders,
	MinioProviders,
)
