// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cloud_tinamic/rpc/vector_service/repo"
)

// Injectors from wire.go:

func InitVectorService() *VectorServiceImpl {
	pgPool := repo.NewPgPool()
	cache := repo.InitCache()
	vectorServiceRepo := repo.NewVectorServiceRepoImpl(pgPool, cache)
	vectorServiceImpl := NewVectorServiceImpl(vectorServiceRepo)
	return vectorServiceImpl
}
