[database]
host = "1.92.113.25"
user = "postgres"
password = "admin321"
port=5432
dbname = "tinamic"
#[database]
#host = "172.29.160.1"
#user = "postgres"
#password = "admin"
#port=5433
#dbname = "tinamic"
[minio]
endpoint="39.101.164.253:9000"
access_key="ugNa8yDGzk4gESCATs06"
secret_key="ruiC05DkvnxxNZrMba5kUbgux8oJLreYuulXhryw"