[database]
host = "1.92.113.25"
user = "postgres"
password = "admin321"
port=5432
dbname = "tinamic"
#[database]
#host = "172.29.160.1"
#user = "postgres"
#password = "admin"
#port=5433
#dbname = "tinamic"